
var nouns = ["doges", "Gilmore Girls", "breakfast tots", "Polariods", "great times", "long distance running", "having to go to the bathroom", "hating on the dwags", "knocking people's socks off", "rap music", "Enya", "listening to records with his boys", "Dwin", "Lew Bear", "living in the Hirsch House", "Home Park", "the Yackets", "being in a frat", "something about roadtrips", "frat snapping", "7000-mile car rides", "the Pacific Northwest", "Watson Griffith", "Pokemon Red Version", "Highland Bakery", "Runscape", "himself", "gluten", "The Blue Man Group", "caprise salad", "overestimating beer", "Cleve", "LOLa Doge", "soul patches", "Mama Squires", "coff", "going thru a Dutch brother's drive thru and accidentally ordering six double rebels and then it ends up costing 50 dollars so a girl sees the out-of-state driver's license and gives it all for free", "saying \"Lordie, Lordie!\"", "Warby Parker's", "Willy's Mexicana which is way better than Moe's", "Hankook", "these days", "the confidence to overcome self-doubt which keeps you from becoming your best self", "peas", "guessing who is singing the song playing at a coffee shop", "going to Zed concerts", "not going to Zed concerts", "living above the poverty line", "listening to Noah Gundersen new releases on porches", "Garrels", "Birkenstocks", "Cookout before it came to Atlanta and got not cool", "Starbucks competitors", "Napsacks", "Jesus", "silly socks", "chicken", "unwinding after a long day of screaming (all day)", "jQuery", "the word \"weirdly\"", "Stephen Dubbert", "mouth-breathers", "forbidden Brazilian loves", "Starlee Kine", "his roomies", "getting stuff taken care of", "One Direction (before they took their hiatus). So sad for 14-year-olds everywhere", "parking in the yard", "Sig Ep", "Willy Bum Bum", "Brad Ware", "Peeves from Harry Potter", "turkey burgers", "high schoolers", "Penny and Sparrow", "Brazilian billiards (the kind where all the balls are the same color)", "DJ Baby Bok Choy", "Wes Anderson", "going over to the FoFoFo", "rummage artifacts of a time long-past", "Beats by Dre", "Anna Schuler (how 'bout it?)", "Amazon Prime", "Se7en", "jazz", "having to remember whether or not he locked his car", "muffin tops", "Andrew Bird", "beeeeeerz", "Ikea", "pickle that", "put a bird on it"];

var gerunds = ["dogeing", "going back to the basics", "kickin' it", "around town", "swinging", "hittin' up da clubz", "strangely energetic", "gettin' down", "having great times", "under his bed", "with Nikki", "scrolling through the Instant Gram", "at church", "wondering around Centennial Olympic Park wondering why he went over there", "calling dibs", "scanning QR code posters", "talking to Davis Mitchell", "networking", "dogeing with his boyz", "around these parts", "watching The Land Before Time", "vandalizing the city", "listening to the Tune Yards", "under a heavily-loaded benchpress", "maintaining the Shire", "getting down to business", "scanning QR codes", "playing Spikeball with Sadie Roberston like all day", "drinking", "at the dentist", "watching Kyle Mooney videos", "at his wit's end", "scratching an itch", "going through the Chick-fil-a Drive Thru", "drinking coff", "crying alone", "looking at doge pictures on the internet", "working at Coke", "living in Seattle", "learning the Jedi trade", "being in a frat", "at Terminal West", "expressing himself", "at the Hirsch House", "sitting in Lewis' room coming up with a word bank of mad lib words", "at the beach", "under the sea", "eating his favorite doge food", "protesting GMOs", "embracing GMOs", "cooking up a storm", "raging", "chillin", "getting to the bottom of things", "watching Gilmore Girls", "eating tater tots", "taking sweet pics out West", "sleeping", "under the weather", "near but not in the CULC", "balling", "kickin it around town", "dogeing in the Shire", "thinking about life in the Shire", "wondering why abbreviation is such a long word", "howling at the moon", "over yonder", "making oblique music references", "with Lewis", "under the impression that he was allowed to park there", "apologizing", "fratting", "attempting to flirt", "boofing", "getting his FIF on", "squirreling around", "watching Chopped", "whirling dervishes", "saying \"That's how we do it\"", "getting electrocuted by switch gears", "throwing house warming parties during which the guests bring art in exhange for beeeeerz"];
var websites = ["edwinchoate.com", "alexmiller.ninja", "penisland.net", "whorepresents.com", "speedofart.com", "gotahoenorth.com", "dicksonweb.com", "therapist.com", "budget.co.ck", "oldmanshaven.com", ];
var bodyParts = ["knees", "elbows", "toes", "pits", "nostrils", "eye sockets", "knee caps", "pinkies", "Adam's apple", "forehead"];

var noun = nouns[Math.floor(Math.random() * nouns.length)];
var gerund = gerunds[Math.floor(Math.random() * gerunds.length)];
var website = websites[Math.floor(Math.random() * websites.length)];
var bodyPart = bodyParts[Math.floor(Math.random() * bodyParts.length)];


$(document).ready(function () {
    $(".noun").text(noun);
    $(".gerund").text(gerund);
    $(".website").replaceWith("<a href=\"http://" + website + "\" target=\"_blank\">" + website + "</a>");
    $(".body-part").text(bodyPart);
});


console.log(nouns.length + " nouns");
console.log(gerunds.length + " gerunds");
console.log(websites.length + " websites");
console.log(bodyParts.length + " body parts");